### PR TITLE
Colored noise and IR convolution deformers added

### PR DESCRIPTION
**Pull request by yeliuyChuy**
colorednoise.py and ir.py added now.

---
This change is [Reviewable](https://reviewable.io/reviews/bmcfee/muda/67)

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for adding this!  Can you rebase this PR off the current master so that it only includes your changes and not the entire history?

**Comment by bmcfee** [comment]
@yeliuyChuy I just fixed the travis builds on master; can you pull and rebase one more time so the tests run properly on this PR?  Thanks!

**Comment by yeliuyChuy** [comment]
@bmcfee just made the changes as requested, could you help me check with that?

**Comment by bmcfee** [comment]
Thanks again for all your work on this!

**Pull request merged**
