### PR TITLE
Addressed deprecation of pitch_hz namespace in the pitch deformer

### PR DESCRIPTION
**Pull request by cwitkowitz**
This change is [Reviewable](https://reviewable.io/reviews/bmcfee/muda/68)

### CODE REVIEW

**Comment by cwitkowitz** [comment]
Changes should also be made for the deprecation of pitch_midi, but I only needed to fix pitch_hz for now...

**Comment by bmcfee** [comment]
Thanks for doing this!  Would you mind rolling back the deletion of `pitch_hz`?  I know it's deprecated, but there's no harm in keeping support for it here.  Adding `pitch_contour` is :100: though.

**Comment by cwitkowitz** [comment]
Hold off on completing the request. I'm seeing an error on my side.

**Comment by cwitkowitz** [comment]
Alright. Should be ready to go. My environment was not treating the methods as static for some reason. Restarting fixed it.

**Comment by cwitkowitz** [comment]
Hey. Just want to remind you that this is good to merge.

**Comment by bmcfee** [comment]
Thanks for the reminder, and the PR!  :shipit:

**Pull request merged**
